name: 02 Runner Info

on: workflow_dispatch

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
    - name: Check Bash Version
      run: bash --version
    - name: Check Python version
      run: python3 --version
    - name: Check Node.js version
      run: node -v
    - name: List installed packages (first 10)
      run: dpkg -l | head

