name: 09 Matrix Demo

on: workflow_dispatch

jobs:
  matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [10,12,14]
    steps:
      - run: echo "Node version ${{ matrix.version }}"
