name: Cache Demo

on: push

jobs:
  cache-example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v4
        with:
          path: my-cache
          key: cache-${{ github.run_id }}
      - run: mkdir -p my-chache &&& echo "Hello" > my-cache/msg.txt
      - run: cat my-cache/msg.txt
