name: Inspect Runner

on:
  workflow_dispatch

jobs:
  show-files:
    runs-on: ubuntu-latest
    steps:
      - name: Before Checkout CWD
        run: pwd
      - name: Checkout Repository
        uses: actions/checkout@v4
      - run: ls -R
      - name: After Checkout CWD
        run: pwd

