name: Inspect Runner

on:
  workflow_dispatch

jobs:
  env-demo:
    runs-on: ubuntu-latest
    env:
      LOCAL_VAR: "Heelo from job env"
    steps:
      - run: echo "Actor -> $GITHUB_ACTOR"
      - run: echo "Commit SHA ->  $GITHUB_SHA"
      - run: echo "Local var -> $LOCAL_VAR"

