name: Use My Action

on:
  workflow_dispatch

jobs:
  use-action:
    runs-on: ubuntu-latest
    steps:
      - name: Use My Action
        uses: hypatia-tile/learn-ghaction02@v1
        with:
          who: Sinokun
